site_name: LLM Ripper
theme:
  name: material
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Beginners: beginners.md
  - Maintainers: maintainers.md
  - Guides:
    - Transplant Strategies: guides/transplant_strategies.md
    - Validation: guides/validation.md
    - Causal Tracing: guides/causal_tracing.md
    - UQ & Routing: guides/uq_routing.md
    - Interoperability: guides/interop.md
    - Safety & Reporting: guides/safety_reporting.md
    - End-to-End Pipeline: guides/end_to_end.md
  - Architecture: architecture.md
  - API: api.md
repo_url: https://github.com/qrv0/LLM-Ripper
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - pymdownx.superfences
  - toc:
      permalink: true
